// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3_3W0JkRp9gZln2pp9TMVP_3qIM9kt0s',
    appId: '1:536335012908:android:c5ae97933ed329b16c6d89',
    messagingSenderId: '536335012908',
    projectId: 'quickcart-5ade3',
    storageBucket: 'quickcart-5ade3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2aocLKTzhTo2dnNAFlPKh1aXH9o1wHSY',
    appId: '1:536335012908:ios:9571e41104b8c6d56c6d89',
    messagingSenderId: '536335012908',
    projectId: 'quickcart-5ade3',
    storageBucket: 'quickcart-5ade3.appspot.com',
    iosClientId: '536335012908-f6vj6lalrgmlj8ak5agjsjg34th2ts8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickcart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2aocLKTzhTo2dnNAFlPKh1aXH9o1wHSY',
    appId: '1:536335012908:ios:f9e3e230568aa8ed6c6d89',
    messagingSenderId: '536335012908',
    projectId: 'quickcart-5ade3',
    storageBucket: 'quickcart-5ade3.appspot.com',
    iosClientId: '536335012908-7atf63veu1gl597dbres0e7t1en2bggt.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickcart.RunnerTests',
  );
}
